name: Build and Deploy Storybook for Vercel
on: 
  push:
    branches:
      - 'main'
      - '!storybook-deploy'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge main to storybook-deploy
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: storybook-deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
